keys:
  - &primary age164jvgs39v4qzmke0h2ua4tygtgmchnjvexfgvtjxvl9hd07ugdfqqw95at
  - &auriga age1p57454z8mpvd4acley0vh0c9mphrmqyztynvwua23p9ly8a8meqsey3xv0
creation_rules:
  - path_regex: ^secrets.yaml$
    key_groups:
      - age:
          - *primary
          - *auriga
